Rental service implementation
jv-jun23-jvavaTeam/car-sharing-app pull request #30
Opened 2023-10-03 18:35 UTC by CodeWebWeaver

This request includes:
- RentalServiceImpl logic
- removed @Repository annotation from UserRepository interfacce
- moved PaymentServiceImpl to impl folder

2023-10-03 19:29 UTC, holsoni approved these changes
LGTM!

2023-10-04 05:59 UTC, Dimagaa requested changes
Great Job! Lets improve it!

2023-10-04 05:59 UTC, Dimagaa commented on src/main/java/com/jvavateam/carsharingapp/repository/SpecificationProvider.java
> +}
Can we make `getSpecification()` method generic? What if we want to search by rental date?

2023-10-04 05:59 UTC, Dimagaa commented on src/main/java/com/jvavateam/carsharingapp/service/impl/RentalServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Car with provided id not found"));
I think we should use Car Service instead Car Repository

2023-10-04 05:59 UTC, Dimagaa commented on src/main/java/com/jvavateam/carsharingapp/service/impl/RentalServiceImpl.java
> +        Long currentUserId = userRepository.getCurrentUser().getId();
We can check it in Rental Repository

2023-10-04 05:59 UTC, Dimagaa commented on src/main/java/com/jvavateam/carsharingapp/service/impl/RentalServiceImpl.java
> +    }
Lets try do it in repository

2023-10-04 11:33 UTC, closed without merging