Improved logic in payment and rental services
jv-jun23-jvavaTeam/car-sharing-app pull request #44
Opened 2023-10-04 19:25 UTC by holsoni

2023-10-04 20:02 UTC, Dimagaa requested changes
Well done!

2023-10-04 20:02 UTC, Dimagaa commented on src/main/java/com/jvavateam/carsharingapp/controller/PaymentController.java
> +        System.out.println("hello");
Hello)

2023-10-04 20:33 UTC, Dimagaa approved these changes

2023-10-05 07:01 UTC, CodeWebWeaver approved these changes

2023-10-05 07:30 UTC, merged